config:
    AZURE_SUBSCRIPTION_ID: "<your-subscription-id>"  
    AZURE_RESOURCE_GROUP: "<your-resource-group>" 
    AZURE_WORKSPACE: "<your-workspace-name>"
    HF_TOKEN: "<Your token>" # Please modify to your Hugging Face token
    HF_MODEL_NAME_OR_PATH: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B" #"deepseek-ai/DeepSeek-R1-Distill-Llama-70B"
    IS_DEBUG: true

serve:
    azure_env_name: "llm-serving-vllm-2025-02-23-1" # Please modify to your AzureML env name
    azure_model_name: "vllm-docker-1" # Please modify to your AzureML model name
    azure_endpoint_name: "endpoint-docker-1"
    azure_deployment_name: "blue"
    azure_serving_cluster_size: "Standard_NC24ads_A100_v4" # 1 x A100 (80GB) # azure_serving_cluster_size: "Standard_ND40rs_v2" # 1 x A100 (80GB)